-- -*- mode: sql; sql-product: firebird -*-

--"id"integer generated by default as identity primary key
--"id"serial primary key
-- "Fecha" timestamp default 'NOW'

--
-- Jafra
--

--
-- Con el siguiente esquema en PostgreSQL:
--
--
-- Significa que el comando funcionó:
-- 1: at ./connectivity/source/drivers/firebird/StatementCommonBase.cxx:459
--
-- generamos un "Pedido" y luego agregamos las "Cantidad"es de los n "Producto"s de ese pedido en la tabla venta, así, con los "Precio"s actuales de cada producto se puede saber el total a pagar de cada pedido.
-- Con el tiempo, cada "Producto" actualiza su "Precio" (algunos bajan y otros suben), ¿cómo le puedo hacer 

-- connect "localhost:/home/asarch/Documentos/Jafra - Firebird.fdb" user sysdba password xpgbjapan;


create table "Vendedor" (
    "id" integer generated by default as identity primary key,
    "Nombre" blob sub_type 1,
    "Apellido paterno" blob sub_type 1,
    "Apellido materno" blob sub_type 1,
    "Fecha" timestamp default 'NOW'
);

create table "Cliente" (
    "id" integer generated by default as identity primary key,
    "Nombre" blob sub_type 1,
    "Apellido paterno" blob sub_type 1,
    "Apellido materno" blob sub_type 1,
    "Fecha" timestamp default 'NOW'
);

create table "Pedido" (
    "id" integer generated by default as identity primary key,
    "Vendedor" integer references "Vendedor"("id") on delete cascade on update cascade,
    "Cliente" integer references "Cliente"("id") on delete cascade on update cascade,
    "Fecha" timestamp default 'NOW'
);

create table "Categoría" (
    "id" integer generated by default as identity primary key,
    "Nombre" blob sub_type 1,
    "Fecha" timestamp default 'NOW'
);

create table "Marca" (
    "id" integer generated by default as identity primary key,
    "Nombre" blob sub_type 1,
    "Fecha" timestamp default 'NOW'
);

create table "Producto" (
    "id" integer generated by default as identity primary key,
    "Nombre" blob sub_type 1,
    "Categoría" integer references "Categoría"("id") on delete cascade on update cascade,
    "Marca" integer references "Marca"("id") on delete cascade on update cascade,
    "Precio" numeric(10, 2),
    "Fecha" timestamp default 'NOW'
);

create table "Venta" (
    "id" integer generated by default as identity primary key,
    "Pedido" integer references "Pedido"("id") on delete cascade on update cascade,
    "Producto" integer references "Producto"("id") on delete cascade on update cascade,
    "Cantidad" integer,
    "Precio" numeric(10, 2),
    "Descuento" numeric(10, 2),
    "Fecha" timestamp default 'NOW'
);

create table "Comentario producto" (
    "id" integer generated by default as identity primary key,
    "Producto" integer references "Producto"("id") on delete cascade on update cascade,
    "Comentario" blob sub_type 1,
    "Fecha" timestamp default 'NOW'
);

create table "Comentario venta" (
    "id" integer generated by default as identity primary key,
    "Venta" integer references "Venta"("id") on delete cascade on update cascade,
    "Comentario" blob sub_type 1,
    "Fecha" timestamp default 'NOW'
);
   
create table "Comentario pedido" (
    "id" integer generated by default as identity primary key,
    "Pedido" integer references "Pedido"("id") on delete cascade on update cascade,
    "Comentario" blob sub_type 1,
    "Fecha" timestamp default 'NOW'
);

create table "Histórico" (
    "id" integer generated by default as identity primary key,
    "Producto" integer references "Producto"("id") on delete cascade on update cascade,
    "Precio" numeric(10, 2),
    "Fecha" timestamp default 'NOW'
);

create table "Inventario" (
    "id" integer generated by default as identity primary key,
    "Producto" integer references "Producto"("id") on delete cascade on update cascade,
    "Cantidad" integer,
    "Fecha" timestamp default 'NOW'
);

create table "Pago" (
    "id" integer generated by default as identity primary key,
    "Pedido" integer references "Pedido"("id") on delete cascade on update cascade,
    "Cantidad" numeric(10, 2),
    "Fecha" timestamp default 'NOW'
);

insert into "Categoría"("Nombre") values ('Perfume para dama');
insert into "Categoría"("Nombre") values ('Perfume para caballero');
insert into "Categoría"("Nombre") values ('Desodorante en aerosol para dama');
insert into "Categoría"("Nombre") values ('Desodorante en aerosol para caballero');
insert into "Categoría"("Nombre") values ('Desodorante en roll-on para dama');
insert into "Categoría"("Nombre") values ('Desodorante en roll-on para caballero');
insert into "Categoría"("Nombre") values ('Perfume para niña');
insert into "Categoría"("Nombre") values ('Perfume para niño');
insert into "Categoría"("Nombre") values ('Desodorante en aerosol para niña');
insert into "Categoría"("Nombre") values ('Desodorante en aerosol para niño');
insert into "Categoría"("Nombre") values ('Desodorante en roll-on para niña');
insert into "Categoría"("Nombre") values ('Desodorante en roll-on para niño');

insert into "Cliente"("Nombre", "Apellido paterno", "Apellido materno") values ('Alef Sheridan Ariel', 'Ramírez', 'Chiñas');
insert into "Cliente"("Nombre", "Apellido paterno", "Apellido materno") values ('Adam Jean Michael', 'Ramírez', 'Chiñas');
insert into "Cliente"("Nombre", "Apellido paterno", "Apellido materno") values ('Marcks Anthony', 'Ramírez', 'Luis');
insert into "Cliente"("Nombre", "Apellido paterno", "Apellido materno") values ('Richard David', 'Ramírez', 'Luis');

insert into "Marca"("Nombre") values ('Jafra');
insert into "Marca"("Nombre") values ('Tupperware');
insert into "Marca"("Nombre") values ('Arabela');
insert into "Marca"("Nombre") values ('Betterware');
insert into "Marca"("Nombre") values ('Avon');
insert into "Marca"("Nombre") values ('Fuller');
insert into "Marca"("Nombre") values ('Stanhome');

insert into "Vendedor"("Nombre", "Apellido paterno", "Apellido materno") values ('Reyna', 'Luis', 'Altamirano');
insert into "Vendedor"("Nombre", "Apellido paterno", "Apellido materno") values ('Elena', 'Luis', 'Altamirano');
insert into "Vendedor"("Nombre", "Apellido paterno", "Apellido materno") values ('Betsaida Nathalí', 'Tamariz', 'Chiñas');
insert into "Vendedor"("Nombre", "Apellido paterno", "Apellido materno") values ('Rubicel', 'Pérez', 'Gómez');

insert into "Producto"("Nombre", "Categoría", "Marca", "Precio") values ('JF9 Verde', 2, 1, 189.45);
insert into "Producto"("Nombre", "Categoría", "Marca", "Precio") values ('JF9 Rojo', 2, 1, 199.45);
insert into "Producto"("Nombre", "Categoría", "Marca", "Precio") values ('JF9 Negro', 2, 1, 210.85);
insert into "Producto"("Nombre", "Categoría", "Marca", "Precio") values ('JF9 Azul', 2, 1, 189.45);

-- 1: firebird_sdbc error:
-- *Dynamic SQL Error
-- *SQL error code = -104
-- *Token unknown - line 21, column 1
-- *create
-- caused by
-- 'isc_dsql_prepare'
--  at ./connectivity/source/drivers/firebird/Util.cxx:69

-- 1: firebird_sdbc error:
-- *Dynamic SQL Error
-- *SQL error code = -104
-- *Token unknown - line 21, column 1
-- *create
-- caused by
-- 'isc_dsql_prepare'
--  at ./connectivity/source/drivers/firebird/Util.cxx:69

-- 1: firebird_sdbc error:
-- *Dynamic SQL Error
-- *SQL error code = -104
-- *Token unknown - line 27, column 1
-- *create
-- caused by
-- 'isc_dsql_prepare'
--  at ./connectivity/source/drivers/firebird/Util.cxx:69
--
drop table "Histórico";
drop table "Inventario";
drop table "Comentario producto";
drop table "Comentario venta";
drop table "Pago";
drop table "Venta";
drop table "Pedido";
drop table "Producto";
drop table "Vendedor";
drop table "Cliente";
drop table "Marca";
drop table "Categoría";
